Implement basic control and monitor
snu-quiqcl/wlm-server-legacy pull request #6
Opened 2024-05-14 10:14 UTC by BECATRUE

This closes #4.

2024-05-14 11:07 UTC, kangz12345 requested changes

2024-05-14 11:07 UTC, kangz12345 commented on main.py
> +async def set_exposure(channel: int, exposure: float):
Let's denote the unit in the name of the argument, e.g. `exposure_s`.

2024-05-14 11:07 UTC, kangz12345 commented on main.py
> +async def get_exposure(channel: int) -> float:
I'm not sure what is the best way to specify the unit of the exposure time.

2024-05-16 02:16 UTC, BECATRUE commented on main.py
> +async def get_exposure(channel: int) -> float:
How about specify the unit in the method name, e.g., `get_exposure_s()`? @kangz12345

2024-05-16 04:15 UTC, kangz12345 commented on main.py
> +async def get_exposure(channel: int) -> float:
That sounds good!

2024-11-21 16:18 UTC, BECATRUE commented
We decided to implement a WLM server in the `wlm-server` repository, hence I close this PR.

2024-11-21 16:18 UTC, closed without merging